import Head from "next/head";

// import { Inter } from "@next/font/google";
import Link from "next/link";
import styled from "styled-components";

const Hero = styled.section`
  height: 80vh;
  display: flex;
`;
const Left = styled.div`
  flex: 2;
  display: flex;
  background: url("/left.png") no-repeat center;
  background-size: cover;
  object-fit: cover;
  align-items: center;
  justify-content: center;
`;

const Content = styled.div`
  width: 60%;

  & h1 {
    font-weight: 700;
    font-size: 70px;
    margin-bottom: 2.4rem;
    /* or 114% */

    letter-spacing: 0.2px;

    /* text-color */

    color: #252b42;
  }

  & p {
    font-weight: 500;
    font-size: 20px;
    line-height: 30px;
    /* identical to box height, or 150% */
    font-family: Montserrat, sans-serif;

    letter-spacing: 0.2px;

    /* second-text-color */

    color: #737373;
  }
  & span {
    display: inline-block;
    font-family: Raleway, sans-serif;
    font-style: normal;
    font-weight: 300;
    font-size: 18px;
    line-height: 26px;
    /* identical to box height, or 144% */
    margin-top: 2.4rem;
    letter-spacing: 0.2px;

    /* second-text-color */

    color: #737373;
  }

  & div {
    display: flex;
    align-items: center;
    margin-top: 3.9rem;
    gap: 3rem;

    & button {
      background: #b73225;
      border-radius: 5px;
      font-family: Raleway, sans-serif;
      font-style: normal;
      font-weight: 500;
      font-size: 15px;
      line-height: 25px;
      /* identical to box height, or 167% */
      border: none;
      padding: 1.5rem 4rem;
      letter-spacing: 0.2px;
      cursor: pointer;
      /* light-text-color */

      color: #ffffff;
    }

    & p {
      font-family: Oswald, sans-serif;
      font-style: normal;
      font-weight: 500;
      font-size: 26px;
      line-height: 30px;
      /* identical to box height, or 115% */

      letter-spacing: 0.1px;

      /* primary-text-color */

      color: #b73225;
    }
  }
`;

const Right = styled.div`
  flex: 2;
  background: url("/right.png") no-repeat center;
  background-size: cover;
  object-fit: cover;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Left>
          <Content>
            <h1>The Lawson Collection</h1>
            <p>SUMMER 2020</p>
            <span>We know how large objects will act,</span>
            <div>
              <Link href="/products">
                <button>Shop Now</button>
              </Link>

              <p>$19.00</p>
            </div>
          </Content>
        </Left>
        <Right></Right>
      </Hero>
    </>
  );
}
